# Project information
site_name: ""
site_url: https://w3f.github.io/polkadot-wiki-mkdocs
site_author: Web3 Foundation Technologies
site_description: >-
  High-level documentation for the Polkadot Ecosystem.

# Repository
repo_name: w3f/polkadot-wiki-mkdocs
repo_url: https://github.com/w3f/polkadot-wiki-mkdocs

# Copyright
copyright: Copyright &copy; 2017 - 2025 Web3 Foundation Technologies

# Configuration
theme:
  name: material
  custom_dir: material-overrides
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.tabs 
    - navigation.indexes 
    - navigation.top 
    - navigation.path
    - content.action.edit
  palette: 
    scheme: default
    primary: white
    accent: pink
  favicon: assets/Polkadot_Favicon.png
  logo: assets/wiki-logo.svg

# Plugins
plugins:
  - awesome-pages
  - search

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/Polkadot
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/polkadot
    - icon: fontawesome/brands/github
      link: https://github.com/paritytech/polkadot-sdk
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCB7PbjuZLEba_znc7mEGNgw
    - icon: fontawesome/brands/discord
      link: https://dot.li/discord
extra_css:
  - stylesheets/extra.css
  - stylesheets/MessageBox.css
extra_javascript:
  - assets/MessageBox.js

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - codehilite
  - toc
  - tables
  - sane_lists
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.arithmatex
  - attr_list
  
    
  
