site_name: Polkadot Wiki
site_url: https://w3f.github.io/polkadot-wiki-mkdocs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: material-overrides
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.tabs 
    - navigation.indexes 
    - navigation.top 
    - navigation.path
    - content.action.edit
  palette: 
    scheme: default
    primary: pink
    accent: pink
  logo: assets/logo.png

plugins:
  - awesome-pages
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  
    
  
